[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "http://${{secrets.BACKEND_HOST}}/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
